esphome:
  name: "wopr"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/ssieb/custom_components
    components: [ ht16k33_alpha ]

time:
  - platform: homeassistant
    id: my_time

#BUTTONS
binary_sensor:
  - platform: gpio
    pin: 14
    name: BTN1
    filters:
      - delayed_on: 10ms
  - platform: gpio
    pin: 15
    name: BTN2
    filters:
      - delayed_on: 10ms
  #HAXORZ_EDITION
  - platform: gpio
    pin: 32
    name: BTN3
    filters:
      - delayed_on: 10ms
  - platform: gpio
    pin: 33
    name: BTN4
    filters:
      - delayed_on: 10ms

#RGB LEDS
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: 27
    num_leds: 5
    name: "DEFCON"
    id: defcon
  - platform: partition
    name: "DEFCON1"
    segments:
      - id: defcon
        from: 0
        to: 0
  - platform: partition
    name: "DEFCON2"
    segments:
      - id: defcon
        from: 1
        to: 1
  - platform: partition
    name: "DEFCON3"
    segments:
      - id: defcon
        from: 2
        to: 2
  - platform: partition
    name: "DEFCON4"
    segments:
      - id: defcon
        from: 3
        to: 3
  - platform: partition
    name: "DEFCON5"
    segments:
      - id: defcon
        from: 4
        to: 4


#ALPHA DISPLAY
i2c:    
  sda: 21
  scl: 22

text_sensor:
  - platform: template
    name: "WOPR_DISPLAY"
    id: wopr_display

display:
  - platform: ht16k33_alpha
    address: 0x70
    scroll: true
    scroll_speed: 250ms
    scroll_dwell: 2s
    scroll_delay: 3
    lambda: |-
          it.strftime("  %H %M %S", id(my_time).now());
    secondary_displays:
      - address: 0x72
      - address: 0x74